[workspace]
members = ["crates/*"]
exclude = ["ide/src/tests/mock_project"]
resolver = "2"

[workspace.dependencies]
rustc_plugin = {git = "https://github.com/zgrannan/rustc_plugin", branch = "pcg-flowistry"}
rustc_utils = {git = "https://github.com/zgrannan/rustc_plugin", branch = "pcg-flowistry"}
indexical = {version = "0.3.1", default-features = false, features = ["rustc"]}

[profile.bench]
debug = true
